### PR TITLE
Sort files with numerical order 

### PR DESCRIPTION
**Pull request by Harsh-br0**
^__^

### CODE REVIEW

**Comment by Krishna-Singhal** [comment]
Fuckin disaster

**Comment by Krishna-Singhal** [comment]
IMG_20210526_232435
😑😑

**Comment by Harsh-br0** [comment]
What a non sense error raised by deepsource 
ಠ,_｣ಠ

**Comment by rking32** [comment]
Hi @Harsh-br0, may i know drawbacks in current `sort` method

**Comment by Harsh-br0** [comment]
Sup @rking32  , currently it sorts with first character of filename
Like if the folder have
```
 ["1.mp3", "2.mp3", "11.mp3"]
```
 so it sorts it in this order 
```
[
 "1.mp3",
 "11.mp3",
 "2.mp3"
]
```
With this commit , i think it will try to check starting digits of file to sort numerically otherwise it will sort normally like always it does
If its useless like [he thinks](https://github.com/UsergeTeam/Userge/pull/341#issuecomment-848995649) , i can close this PR and will make something useful next time :)

**Comment by rking32** [comment]
> Sup @rking32 , currently it sorts with first character of filename
> Like if the folder have
> 
> ```
>  ["1.mp3", "2.mp3", "11.mp3"]
> ```
> 
> so it sorts it in this order
> 
> ```
> [
>  "1.mp3",
>  "11.mp3",
>  "2.mp3"
> ]
> ```
> 
> With this commit , i think it will try to check starting digits of file to sort numerically otherwise it will sort normally like always it does
> If its useless like [he thinks](https://github.com/UsergeTeam/Userge/pull/341#issuecomment-848995649) , i can close this PR and will make something useful next time :)

Nice feature thanks. Can you make it supports for some than `2` digits.

**Input**: ` ["11.mp3", "22.mp3", "111.mp3", "110.mp3"]`
**Output**: `['11.mp3', '111.mp3', '110.mp3', '22.mp3']`

Also you can move this function to `utils`. So we can reuse it whenever we want. :)

**Comment by Harsh-br0** [comment]
@rking32  thanks to mention , i c that i forgot to replace test limitation of `{,2}` with a `+` 😅

**Comment by rking32** [comment]
nice

**Comment by rking32** [comment]
Finally, Can you check `re.search(...)` is `None` or not before call `group()`.

Ex: `check_numerical_order("test.mp3")`
Output: `AttributeError: 'NoneType' object has no attribute 'group'`

**Comment by Krishna-Singhal** [comment]
> Sup @rking32 , currently it sorts with first character of filename
> Like if the folder have
> 
> ```
>  ["1.mp3", "2.mp3", "11.mp3"]
> ```
> 
> so it sorts it in this order
> 
> ```
> [
>  "1.mp3",
>  "11.mp3",
>  "2.mp3"
> ]
> ```
> 
> With this commit , i think it will try to check starting digits of file to sort numerically otherwise it will sort normally like always it does
> If its useless like [he thinks](https://github.com/UsergeTeam/Userge/pull/341#issuecomment-848995649) , i can close this PR and will make something useful next time :)

well i thinks too much hard work

**Pull request merged**
