### PR TITLE
Delete userge.png

### PR DESCRIPTION
**Pull request by KelvinCrag**

### CODE REVIEW

**Comment by KelvinCrag** [comment]
Sorry 😞

**Comment by Harsh-br0** [comment]
> Sorry 😞

No probs but why are you deleting the pic of something which u use?

**Comment by KelvinCrag** [comment]
> No probs but why are you deleting the pic of something which u use?

There's not wrong with the pic.. In fact  I even use it at default in alive command. But I don't just like seeing it in the files I upload remotely. I prefer no thumbnails or the movie file thumbnail :(

**Comment by Harsh-br0** [comment]
Yup , u need to use .dthumb ig
Or set ur default thumb then it will be permanent

**Comment by KelvinCrag** [comment]
Thanks! It worked

**Pull request closed without merging**
