### PR TITLE
Update alive.py

### PR DESCRIPTION
**Pull request by rowdy-hero**

### CODE REVIEW

**Comment by Phyco-Ninja** [comment]
Why this kolaverid?

**Comment by rowdy-hero** [comment]
> Why this kolaverid?

**Comment by Harsh-br0** [comment]
>Why this kolaverid?
Kolaver di*

**Comment by Phyco-Ninja** [comment]
> > Why this kolaverid?
> 
> Kolaveri di*

Me nub sar 🌚 mah friend taught it 🥺

**Pull request closed without merging**
