### PR TITLE
upload: audio_upload: replace space between name and size in caption with newline

### PR DESCRIPTION
**Pull request by yshalsager**
This way caption in RTL languages on files can be shown correctly.

Before:
image

After:
image

### CODE REVIEW

**Comment by Krishna-Singhal** [comment]
> This way caption in RTL languages on files can be shown correctly.
> 
> Before: image
> 
> After: image

Bruh I think before one is better than after

**Comment by yshalsager** [comment]
> Bruh I think before one is better than after

It's not about better or worse, the whole point is to make it compatible with RTL captions, which isn't displayed correctly at the moment.

**Comment by Harsh-br0** [comment]
Seems this guy started a game like thing to compete for more activity among other contributors

**Comment by yshalsager** [comment]
@Harsh-br0 lol no, I am just purposing changes for stuff I face while using the bot daily. If you don't like external contributions it's fine.

**Comment by Krishna-Singhal** [comment]
> It's not about better or worse, the whole point is to make it compatible with RTL captions, which isn't displayed correctly at the moment.

What about this

before
image
after
after
image

isn't filename looks ugly in RTL language ?

**Comment by Harsh-br0** [comment]
> @Harsh-br0 lol no, I am just purposing changes for stuff I encounter while using the bot daily. ~If you don't like external contributions it's fine.~

Chill bro , am not serious about that just mocking around ¯\_(ツ)_/¯

**Comment by yshalsager** [comment]
> > It's not about better or worse, the whole point is to make it compatible with RTL captions, which isn't displayed correctly at the moment.
> 
> What about this
> 
> before image
> 
> after image
> 
> isn't filename looks ugly in RTL language ?

So? :D It's about displaying it properly from right to left, because as you can see in the first screenshot file size interferes with the name causing it to be shown incorrectly (file size first then rest of file name).

**Comment by Krishna-Singhal** [comment]
> So? :D It's about displaying it properly from right to left, because as you can see in the first screenshot file size interferes with the name causing it to be shown incorrectly (file size first then rest of file name).
 Didn't you see this brackets [ ] are not perfect in RTL around file name

**Comment by yshalsager** [comment]
> > So? :D It's about displaying it properly from right to left, because as you can see in the first screenshot file size interferes with the name causing it to be shown incorrectly (file size first then rest of file name).
> 
> its fine if file name is first then file size.

How can it be fine? The current implementation is `f"{path.name} [ {file_size} ]` already, and filename is not shown correctly as I demonstrated.

**Comment by Krishna-Singhal** [comment]
> How can it be fine? The current implementation is `f"{path.name} [ {file_size} ]` already, and filename is not shown correctly as I demonstrated.

but with this implementation, it's not good in LTR

**Comment by yshalsager** [comment]
> > How can it be fine? The current implementation is `f"{path.name} [ {file_size} ]` already, and filename is not shown correctly as I demonstrated.
> 
> but with this implementation, it's not good in LTR languages and majority of LTR languages is greater than RTL

How could it be not good with LTR? I can't understand how a single new line can be this bad.

**Comment by rking32** [comment]
Let's merge this if actually matters to RTL users.

**Comment by yshalsager** [comment]
@rking32 Much appreciated

**Pull request merged**
