### PR TITLE
Update purge.py

### PR DESCRIPTION
**Pull request by APXD-git**
Unable to purge in private chat type error.

### CODE REVIEW

**Comment by Phyco-Ninja** [comment]
Afik, it was disabled intentionally. 🤔

**Comment by APXD-git** [comment]
> Afik, it was disabled intentionally. 🤔

but why its very hectic to delete messages unwanted in private .i everytime need to log in to tgdesktop to delete messages

**Comment by Krishna-Singhal** [comment]
> > Afik, it was disabled intentionally. 🤔
> 
> Its very hectic to unwanted delete messages in private .I everytime need to log in to tgdesktop to delete messages. Please update those changes

If you wanna use purge cmd in private, edit your forked repo
This shud be Off cuz of many users have problem for this,

**Comment by rking32** [comment]
@APXD-git read https://github.com/UsergeTeam/Userge/issues/57 first

anyway you can do [this](https://github.com/UsergeTeam/Userge/pull/113#issuecomment-667698621) if you want it

**Comment by APXD-git** [comment]
Yes i am doing that now. I forked then using that repo after editing. But then how i be able to update please tell me when an update will be released.

**Comment by Krishna-Singhal** [comment]
> Yes i am doing that now. I forked then using that repo after editing. But then how i be able to update when an update will be released . I mean will my forked repo will be auto updated? I am new to github thats why asking please guide me .

Do fork, change code and then add that repo in UPSTREAM_VAR,
simply do .update -{branch} -pull -push and then u can use your updated forked. 🤷🏼

**Comment by APXD-git** [comment]
Yes but what will happen when another update will be released by userge . Will i need to fork and change code each time update is released ??

**Comment by code-rgb** [comment]
> Yes but what will happen when another update will be released by userge . Will i need to fork and change code each time update is released ?? Please tell me.
> After that i will close this request.

use pull bot - https://wei.github.io/pull/

**Comment by APXD-git** [comment]
Thanks

**Pull request closed without merging**
