### PR TITLE
Some fixes + added Gmute 🤘

### PR DESCRIPTION
**Pull request by Krishna-Singhal**
1. Updation in meme [MESSAGE_NOT_MODIFIED]
2. Updation in gban [UserAdminInvalid]
Error occur When user Try to gban a user and both users are admin in some common group.
3. Updation in gadmin [some optimization 😅]
4. Added Gmute for [Userge](https://github.com/usergeteam/userge/issues/95) 🤘 
Now user can Mute a User Globally in groups in which He is Admin 😎

### CODE REVIEW

**Comment by Krishna-Singhal** [comment]
I pushed Commit from my Patch-3 branch then why not shwoing here 😅🤔🤔

**Comment by code-rgb** [comment]
> I pushed Commit from my Patch-3 branch then why not showing here 😅🤔🤔

Push it harder

**Comment by rking32** [comment]
@Krishna-Singhal also can you fix that pep8 errors ?

**Comment by Krishna-Singhal** [comment]
> @Krishna-Singhal also can you fix that pep8 errors ?

yeah fixing 😅

**Pull request merged**
