### PR TITLE
Added new "Info" button for bot pm

### PR DESCRIPTION
**Pull request by NavaneethRenjith8282**
Added a new button called "Info" in botpm.
Added some features and commands for the success of this.
Moved "UsergeTeam", "Repo" and "License" buttons to the info menu.
## Why this...
The button "Info" can be used to show a specific text to those who've started the bot.
`INFO_TEXT` which is used to show this info, can be changed at anytime using `/setinfo` command.

### CODE REVIEW

**Comment by NavaneethRenjith8282** [comment]
Still, can't fix some errors.
Please help.

> @Jigarvarma2005 @Krishna-Singhal @rking32 @Harsh-br0

**Comment by NavaneethRenjith8282** [comment]
Still, can't fix [`elif` after `return`](https://deepsource.io/gh/UsergeTeam/Userge/run/42bf9a01-fb58-4538-8bae-990a53c382c5/python/PYL-R1705) error in [Deepsource](https://deepsource.io/gh/UsergeTeam/Userge/run/42bf9a01-fb58-4538-8bae-990a53c382c5/python/).
Please help.

@Jigarvarma2005 @Krishna-Singhal @Harsh-br0 @rking32
> _**Note**: Any maintainers can edit this pull._

**Comment by Harsh-br0** [comment]
> _**Note**: Any maintainers can edit this pull._

_**Note**: Any maintainer can <s>edit</s> close this pull._

**Comment by Krishna-Singhal** [comment]
Hii @NavaneethRenjith8282 ,

We are glad to see that you are contributing in userge.

These suggestions of yours are useless somewhere and they will also harm the promotion Userge.
Because

If user doesn't press the Info button, then he will not get the link of Userge etc. and due to this he may not be able to know about Userge.

I hope you understand my point.

**Comment by NavaneethRenjith8282** [comment]
Why do you closed this, @krishna-singhal? I can add that buttons back.

**Comment by NavaneethRenjith8282** [comment]
Please, keep this **open**.

**Comment by NavaneethRenjith8282** [comment]
Please, keep this **open**.

**Comment by NavaneethRenjith8282** [comment]
Please, keep this **open**.

**Comment by Krishna-Singhal** [comment]
> Why do you closed this, @Krishna-Singhal? I can add that buttons back.

@NavaneethRenjith8282 Try to understand, still this is invalid PR

**Comment by NavaneethRenjith8282** [comment]
> > Why do you closed this, @Krishna-Singhal? I can add that buttons back.
> 
> @NavaneethRenjith8282 Try to understand, still this is invalid PR

Not invalid... 😐
Since this is already added in other userbots, it is not added in this Userge. And, it is very shame... 
@Krishna-Singhal, try to understand what I'm doing. This thing is already added in other userbots. 
Don't close this pull. Please reopen this. I'll add "[**UsergeTeam**](https://github.com/UsergeTeam)", "[**Repo**](https://github.com/UsergeTeam/Userge)" and "[License](https://github.com/UsergeTeam/Userge/tree/master/license)" buttons in a commit.

**Try to understand why I've opened this pull...**

**Comment by Harsh-br0** [comment]
> Since this is already added in other userbots, it is not added in this Userge. And, it is very shame... 

Userge is not like other userbots , So it doesn't need to copy same format or style ig

**Comment by NavaneethRenjith8282** [comment]
> > Since this is already added in other userbots, it is not added in this Userge. And, it is very shame...
> 
> Userge is not like other userbots , So it doesn't need to copy same format or style ig

Oh! Anyone didn't know the importance of this.

**Comment by NavaneethRenjith8282** [comment]
> Hii @NavaneethRenjith8282 ,
> 
> We are glad to see that you are contributing in userge.
> 
> These suggestions of yours are useless somewhere and they will also harm the promotion Userge. Because
> 
> If user doesn't press the Info button, then he will not get the link of Userge etc. and due to this he may not be able to know about Userge.
> 
> I hope you understand my point.

@Krishna-Singhal... Now, it's wrong...
I've added that buttons back. [View **this commit**](https://github.com/NavaneethRenjith8282/Userge/commit/fdd93d295b35763ec2138236cf1bf2a6ec3811b6) to know more.

**Comment by Krishna-Singhal** [comment]
> > Hii @NavaneethRenjith8282 ,
> > We are glad to see that you are contributing in userge.
> > These suggestions of yours are useless somewhere and they will also harm the promotion Userge. Because
> > If user doesn't press the Info button, then he will not get the link of Userge etc. and due to this he may not be able to know about Userge.
> > I hope you understand my point.
> 
> @Krishna-Singhal... Now, it's wrong... I've added that buttons back. [View **this commit**](https://github.com/NavaneethRenjith8282/Userge/commit/fdd93d295b35763ec2138236cf1bf2a6ec3811b6) to know more.

Whats the use of "Info" button ?

**Comment by NavaneethRenjith8282** [comment]
> Whats the use of "Info" button ?

It can be used to show a description that's visible to anyone who starts the bot.

**Comment by Krishna-Singhal** [comment]
> > Whats the use of "Info" button ?
> 
> It can be used to show a description that's visible to anyone who starts the bot. e.g: If you want to tell anything about the bot, or anything, you can do it there.

{tr}google how to win with kids

**Comment by Harsh-br0** [comment]
Blacklist from repositories

**Comment by NavaneethRenjith8282** [comment]
> {tr}google how to win over kids

```
{tr}google how to win over kids
```

**Comment by Jigarvarma2005** [comment]
> > Whats the use of "Info" button ?
> 
> It can be used to show a description that's visible to anyone who starts the bot. e.g: If you want to tell anything about the bot, or anything, you can do it there.

🤦

**Pull request closed without merging**
