### PR TITLE
Updated requirements.txt

### PR DESCRIPTION
**Pull request by Kunal-Diwan**
Updated googletrans==4.0.0rc1 and fixed httpx==0.13.3

### CODE REVIEW

**Comment by rking32** [comment]
Can you elaborate on this further?

**Comment by Kunal-Diwan** [comment]
> Can you elaborate on this further

googletrans is in old version so Updated to new version

**Comment by rking32** [comment]
What about `httpx`? Why are you suggesting to downgrade that?

**Comment by rking32** [comment]
I locked that because `youtube-search-python` doesn't work properly with `httpx<0.14.2` https://github.com/UsergeTeam/Userge/commit/8c5a517b3a74fffb5c9548ba7acfc1afd78339ae

**Comment by sarah278** [comment]
#13 39.21   Downloading youtube_search_python-1.5.1-py3-none-any.whl (72 kB)
#13 39.27 INFO: pip is looking at multiple versions of emoji to determine which version is compatible with other requirements. This could take a while.
#13 39.27 ERROR: Cannot install -r requirements.txt (line 14) and httpx>=0.14.2 because these package versions have conflicting dependencies.
#13 39.27
#13 39.27 The conflict is caused by:
#13 39.27     The user requested httpx>=0.14.2
#13 39.27     googletrans 3.1.0a0 depends on httpx==0.13.3
#13 39.27
#13 39.27 To fix this you could try to:
#13 39.27 1. loosen the range of package versions you've specified
#13 39.27 2. remove package versions to allow pip attempt to solve the dependency conflict


From my Dockercontainer Build Log...  unable to build it

**Pull request merged**
