### PR TITLE
Fix deepsource (avoid unnecessary escapes)

### PR DESCRIPTION
**Pull request by Jigarvarma2005**

### CODE REVIEW

**Comment by rking32** [comment]
Hi, did you check this command after removing `r`?

**Comment by Jigarvarma2005** [comment]
> Hi, did you check this command after removing `r`?

Need to check

**Comment by Jigarvarma2005** [comment]
> Hi, did you check this command after removing `r`?

I added `r` not removed

**Comment by rking32** [comment]
oo, sorry. my bad :D

Thanks for this :+1:

**Pull request merged**
