### PR TITLE
this should fix (both client responding together for another owner) #328

### PR DESCRIPTION
**Pull request by Krishna-Singhal**

### CODE REVIEW

**Comment by rking32** [comment]
is this the case ?

**Comment by Krishna-Singhal** [comment]
> is this the case ?

maybe that's reason for #328

**Comment by rking32** [comment]
nice. you are r8. this should be the case. but y you ignore first owner ?

lets say i have setup dual mode and i set `OWNER_ID` as different account id. so condition is `False` and both bot and userbot will respond to me.

so this is enough r8 ?
```python
r_m.from_user and r_m.from_user.id in Config.OWNER_ID
```

**Comment by Krishna-Singhal** [comment]
> nice. you are r8. this should be the case. but y you ignore first owner ?
> 
> lets say i have setup dual mode and i set `OWNER_ID` as different account id. so condition is `False` and both bot and userbot will respond to me.
> 
> so this is enough r8 ?
> 
> ```python
> r_m.from_user and r_m.from_user.id in Config.OWNER_ID
> ```

yes you are right, I ignored first owner cuz he is Owner of Userbot 🤔🤔

**Pull request merged**
