### PR TITLE
Perhaps this may fix thumb :/

### PR DESCRIPTION
**Pull request by Phyco-Ninja**

### CODE REVIEW

**Comment by rking32** [comment]
but working for `.upload` command :thinking:

**Comment by Phyco-Ninja** [comment]
🤔 on eval it worked fine,,  
For testing i evaled this 👇 

!eval from userge.utils import take_screen_shot
thumb = await take_screen_shot("downloads/09 - A Goddess for This Corrupt Hot Springs Town!.mkv", 1, "thumbs.png")
await userge.send_video(chat_id=message.chat.id, video="downloads/09 - A Goddess for This Corrupt Hot Springs Town!.mkv", thumb=thumb, supports_streaming=True)


And it worked fine, output was with thumb, 🤔

**Comment by Phyco-Ninja** [comment]
+ i just tested on  .upload it's not giving thumb output :(

**Comment by Phyco-Ninja** [comment]
It is giving some error in logs 
Check this i habe pasted it here https://nekobin.com/gexihegile

**Comment by rking32** [comment]
ok thanks, i'll check it :+1:

**Comment by rking32** [comment]
just fixed this bro. thanks for your detailed explanation

https://github.com/UsergeTeam/Userge/commit/d777d90600a5bcc7b52c4eae7a52403577843183

**Comment by Phyco-Ninja** [comment]
**wew** peru moves

**Pull request closed without merging**
