### PR TITLE
fix: aspect ratio for `Video Stickers`

### PR DESCRIPTION
**Pull request by AsmSafone**
* fix ratio

* Get main aspect ratio from video but one side must be 512.

* `-bufsize 256k ` as output file size won't exceed the tg limit.

### CODE REVIEW

**Comment by rking32** [comment]
thanks

**Comment by AsmSafone** [comment]
> thanks

Pleasure! ✌️ 
Btw if you don't like current implement with `opencv-python-headless`, we can switch to `ffprobe` instead.

**Comment by rking32** [comment]
@AsmSafone thanks for the reply. it is implemented using hachoir :)

**Comment by AsmSafone** [comment]
> @AsmSafone thanks for the reply. it is implemented using hachoir :)

@rking32 Cool 👌

**Pull request merged**
