### PR TITLE
Support for adding private repositories as custom plugins repo

### PR DESCRIPTION
**Pull request by naveennamani**
Now users can add their private repositories in the form

https://<personal_access_token>@github.com/username/repo

More about using/creating personal access tokens
https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token
https://stackoverflow.com/a/66156992/5659132

### CODE REVIEW

**Comment by Krishna-Singhal** [comment]
> Now users can add their private repositories in the form
> 
> https://<personal_access_token>@github.com/username/repo
> 
> More about using/creating personal access tokens
> https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token
> https://stackoverflow.com/a/66156992/5659132

WoW It's too good. 🤗

**Comment by rokibhasansagar** [comment]
shellcheck error happens,
```
Line 196:
_checkCustomPlugins() {
^-- SC1009: The mentioned syntax error was in this function.
                      ^-- SC1073: Couldn't parse this brace group. Fix to allow more checks.
 
Line 197:
    _setupPlugins Custom https://([0-9a-f]{40}@)?github.com/.+/.+ $CUSTOM_PLUGINS_REPO
                                 ^-- SC1036: '(' is invalid here. Did you forget to escape it?
                                 ^-- SC1056: Expected a '}'. If you have one, try a ; or \n in front of it.
                                 ^-- SC1072: Missing '}'. Fix any mentioned problems and try again.
```
Also, bot deployment process stops in init phase

**Comment by rokibhasansagar** [comment]
> shellcheck error happens,
> 
> ```
> Line 196:
> _checkCustomPlugins() {
> ^-- SC1009: The mentioned syntax error was in this function.
>                       ^-- SC1073: Couldn't parse this brace group. Fix to allow more checks.
>  
> Line 197:
>     _setupPlugins Custom https://([0-9a-f]{40}@)?github.com/.+/.+ $CUSTOM_PLUGINS_REPO
>                                  ^-- SC1036: '(' is invalid here. Did you forget to escape it?
>                                  ^-- SC1056: Expected a '}'. If you have one, try a ; or \n in front of it.
>                                  ^-- SC1072: Missing '}'. Fix any mentioned problems and try again.
> ```
> 
> Also, bot deployment process stops in init phase

Fixed after https://github.com/UsergeTeam/Userge/commit/5c1cda2c44f742c969f2410f37cecfc093069d95

**Comment by w0lfrm** [comment]
is there any tutorial for how to add priv repos???

**Pull request merged**
