### PR TITLE
Support for adding user defined plugins repo

### PR DESCRIPTION
**Pull request by naveennamani**
Any user can now add his/her own plugins repository using USER_PLUGINS_REPO env variable.
Use the USER_PLUGINS_REPO structure similar to the userge/userge-plugins repo.

The loaded plugins will be available in userge/plugins/user folder and available as "user" category in the help.

### CODE REVIEW

**Comment by rking32** [comment]
hi @naveennamani, you can just simply fork our plugins repo and add your extra plugins there. why we need an another repo ?

**Comment by naveennamani** [comment]
* Quick plugin development and testing
Users can create plugins in their own repo and test them or share them to others for testing without going through the pull requests waiting in unofficial plugins repo

* There is no way to load temp plugins when you restart. If you use all temp plugins in one user repo, they can always be loaded

* User customisation - I personally don't use many of the unofficial plugins and if I wanted to remove them and retain only those what I use, I cannot delete them in the unofficial repo, instead I can fork and make changes and use my own repo instead

* User privacy: if we can implement support for cloning private git repos a user can create a private repo of plugins that only they wants to use without disturbing

**Comment by rking32** [comment]
yes. but still you can edit this line. very simple. why so much hard work ?
https://github.com/UsergeTeam/Userge/blob/1f67cdd90ca4ee9af7f3e9a3b2b3a7e8fb4ce7e9/init/checks.sh#L163
this PR would be better if we can set custom plugins repo by just adding var like your concept. 
 ```bash
gitClone --depth=1 $USER_PLUGINS_REPO
```

**Comment by naveennamani** [comment]
I just wanted to keep Userge, Userge-Plugins and user-plugins seperate.

If I fork and modify Userge, then I need to always look for changes to userge and update my repo as well.
The same applies for Userge-plugins also. If I want to use userge-plugins along with my own plugins, then this approach can be used.
If I want to use either Userge-plugins or only user-plugins, then we can keep a single variable for CUSTOM_PLUGINS_REPO as mentioned by you.

**Comment by Krishna-Singhal** [comment]
> I just wanted to keep Userge, Userge-Plugins and user-plugins seperate.
> 
> If I fork and modify Userge, then I need to always look for changes to userge and update my repo as well.
> The same applies for Userge-plugins also. If I want to use userge-plugins along with my own plugins, then this approach can be used.
> If I want to use either Userge-plugins or only user-plugins, then we can keep a single variable for CUSTOM_PLUGINS_REPO as mentioned by you.

You can make a telegram channel and add all of your plugins to there if you don't wanna do hardh work, 

Just add var `PLUGINS_CHANNEL_ID` and all plugins in that channel. (very simple)

load all via .loadall (too simple)

**Comment by Krishna-Singhal** [comment]
> * Quick plugin development and testing
>   Users can create plugins in their own repo and test them or share them to others for testing without going through the pull requests waiting in unofficial plugins repo
> * There is no way to load temp plugins when you restart. If you use all temp plugins in one user repo, they can always be loaded
> * User customisation - I personally don't use many of the unofficial plugins and if I wanted to remove them and retain only those what I use, I cannot delete them in the unofficial repo, instead I can fork and make changes and use my own repo instead
> * User privacy: if we can implement support for cloning private git repos a user can create a private repo of plugins that only they wants to use without disturbing any other repos

[There is a way to load temp plugins bruh.](https://github.com/UsergeTeam/Userge/pull/231#issuecomment-757202567)

**Comment by naveennamani** [comment]
> > I just wanted to keep Userge, Userge-Plugins and user-plugins seperate.
> > If I fork and modify Userge, then I need to always look for changes to userge and update my repo as well.
> > The same applies for Userge-plugins also. If I want to use userge-plugins along with my own plugins, then this approach can be used.
> > If I want to use either Userge-plugins or only user-plugins, then we can keep a single variable for CUSTOM_PLUGINS_REPO as mentioned by you.
> 
> You can make a telegram channel and add all of your plugins to there if you don't wanna do hard work,
> 
> Just add var `PLUGINS_CHANNEL_ID` and all plugins in that channel. (very simple)
> 
> load all via .loadall (too simple)

I even tried that using PLUGINS_CHAT_ID, it is suitable to use when the plugin script is finalized, but version controlling the plugins is quite manual.
Assume you've 10 plugins and you updated 3 of them. So, you need to find, delete and upload 3 files or you delete all files from the channel and upload all new versions.
But if you've a repository and you made changes to the files there, they'll be automatically updated on restart or through a command which leads to no manual upload of plugin scripts.

**Comment by rking32** [comment]
@naveennamani yes, i got your idea. its useful in some cases.

**Comment by rking32** [comment]
@naveennamani thanks for your idea. i optimized some codes and gonna merge. peace :)

**Pull request merged**
