### PR TITLE
Paste text same as given (telegraph.py)

### PR DESCRIPTION
**Pull request by Jigarvarma2005**

### CODE REVIEW

**Comment by rking32** [comment]
Hi @Jigarvarma2005, thanks for the interest to this project. Will it work as same if we just use `content = message.reply_to_message.text.html` instead this `markdown` method ?

**Comment by Jigarvarma2005** [comment]
> Hi @Jigarvarma2005, thanks for the interest to this project. Will it work as same if we just use `content = message.reply_to_message.text.html` instead this `markdown` method ?

It's named markdown but it's gives text in html

**Comment by Jigarvarma2005** [comment]
> Hi @Jigarvarma2005, thanks for the interest to this project. Will it work as same if we just use `content = message.reply_to_message.text.html` instead this `markdown` method ?

Hmm

**Comment by Jigarvarma2005** [comment]
@rking32 done ✅, check and merge

**Comment by rking32** [comment]
Seems like `message.reply_to_message.text.html` not parsing properly if text contains both `markdown` and `html`. Sorry for that :(

This works fine
```python
from markdown import markdown

text = "<b>hmm</b>[test](https://google.com)"
print(markdown(text))
```
```'<p><b>hmm</b><a href="https://google.com">test</a></p>'```

**Comment by rking32** [comment]
> Seems like `message.reply_to_message.text.html` not parsing properly if text contains both `markdown` and `html`. Sorry for that :(
> 
> This works fine
> 
> ```python
> from markdown import markdown
> 
> text = "<b>hmm</b>[test](https://google.com)"
> print(markdown(text))
> ```
> 
> `'<p><b>hmm</b><a href="https://google.com">test</a></p>'`

ok, we can ignore this case

**Comment by Jigarvarma2005** [comment]
> Seems like `message.reply_to_message.text.html` not parsing properly if text contains both `markdown` and `html`. Sorry for that :(
> 
> This works fine
> 
> ```python
> from markdown import markdown
> 
> text = "<b>hmm</b>[test](https://google.com)"
> print(markdown(text))
> ```
> 
> `'<p><b>hmm</b><a href="https://google.com">test</a></p>'`

🤔

**Comment by Jigarvarma2005** [comment]
> > Seems like `message.reply_to_message.text.html` not parsing properly if text contains both `markdown` and `html`. Sorry for that :(
> > This works fine
> > ```python
> > from markdown import markdown
> > 
> > text = "<b>hmm</b>[test](https://google.com)"
> > print(markdown(text))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `'<p><b>hmm</b><a href="https://google.com">test</a></p>'`
> 
> ok, we can ignore this case

Why ignore 🤔

**Comment by Jigarvarma2005** [comment]
> Seems like `message.reply_to_message.text.html` not parsing properly if text contains both `markdown` and `html`. Sorry for that :(
> 
> This works fine
> 
> ```python
> from markdown import markdown
> 
> text = "<b>hmm</b>[test](https://google.com)"
> print(markdown(text))
> ```
> 
> `'<p><b>hmm</b><a href="https://google.com">test</a></p>'`

`
"message.reply_to_message.text.html)`

Works fine with mardown and html I tested

**Pull request merged**
