### PR TITLE
fixed issues with kang module

### PR DESCRIPTION
**Pull request by pokurt**
as mentioned by the dev @delivrance : https://t.me/pyrogramlounge/332842
for our case (userbots) to forward the document with true dimensions we have to remove force_filter=True parameter on send_document source.
next up will try and fix dc id (not found any issues with userge) but mine did.
Maintainers of userge can close this pull request if they feel like it but it fixed issues with kang module. Ive tested and confirmed: https://t.me/nanabotsupport/39340

### CODE REVIEW

**Comment by Krishna-Singhal** [comment]
parmotion 😚😁😏😏

**Comment by rking32** [comment]
@pokurt thanks for this. will merge this if we get that stickers issue again :+1:

**Comment by UdaySriHarsha** [comment]
Another Issue


Traceback (most recent call last):
  File "/app/userge/core/methods/decorators/raw_decorator.py", line 292, in template
    await func(types.bound.Message(r_c, r_m, **kwargs))
  File "/app/userge/plugins/fun/kang.py", line 157, in kang_
    await args.edit("Failed to add sticker, use @Stickers "
AttributeError: 'list' object has no attribute 'edit'

**Comment by Krishna-Singhal** [comment]
> Another Issue
> 
> Traceback (most recent call last):
> File "/app/userge/core/methods/decorators/raw_decorator.py", line 292, in template
> await func(types.bound.Message(r_c, r_m, **kwargs))
> File "/app/userge/plugins/fun/kang.py", line 157, in kang_
> await args.edit("Failed to add sticker, use @stickers "
> AttributeError: 'list' object has no attribute 'edit'

do send this in OT group 🤔

**Comment by SurajRaj4542** [comment]
owo

**Comment by rking32** [comment]
now it has been fixed. so closing ...

**Pull request closed without merging**
