### PR TITLE
some changes + fixed deepsource

### PR DESCRIPTION
**Pull request by Krishna-Singhal**
No need of both CONFIGS if Using '-u' flag.

### CODE REVIEW

**Comment by Krishna-Singhal** [comment]
> @Krishna-Singhal, Thanks for updating this PR.
> 
> * In the file [`userge/plugins/misc/instadl.py`](https://github.com/UsergeTeam/Userge/blob/6b2091dcdefe6e5093127f4bbce6d530cf5a884b/userge/plugins/misc/instadl.py):
> 
> > [Line 164:37](https://github.com/UsergeTeam/Userge/blob/6b2091dcdefe6e5093127f4bbce6d530cf5a884b/userge/plugins/misc/instadl.py#L164): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'insta'
> > [Line 167:37](https://github.com/UsergeTeam/Userge/blob/6b2091dcdefe6e5093127f4bbce6d530cf5a884b/userge/plugins/misc/instadl.py#L167): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'insta'
> > [Line 168:45](https://github.com/UsergeTeam/Userge/blob/6b2091dcdefe6e5093127f4bbce6d530cf5a884b/userge/plugins/misc/instadl.py#L168): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'dirname'
> > [Line 171:45](https://github.com/UsergeTeam/Userge/blob/6b2091dcdefe6e5093127f4bbce6d530cf5a884b/userge/plugins/misc/instadl.py#L171): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'dirname'
> > [Line 176:31](https://github.com/UsergeTeam/Userge/blob/6b2091dcdefe6e5093127f4bbce6d530cf5a884b/userge/plugins/misc/instadl.py#L176): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'dirname'
> 
> ##### Comment last updated at 2020-09-27 04:02:14 UTC

O My God 😂😂😂

**Comment by uaudith** [comment]
Why do you say both CONFIGS are not required 
configs are necessary If the use profile is private ?

**Comment by Krishna-Singhal** [comment]
> Why do you say both CONFIGS are not required
> configs are necessary If the use profile is private ?

I think not required if you wanna download all post of a given username.

**Comment by Krishna-Singhal** [comment]
Closing this.

**Pull request closed without merging**
