### PR TITLE
fix for extension of file that are in upper case 😬

### PR DESCRIPTION
**Pull request by gautamajay52**
This doesn't happens alot.
But there is no problem in checking like that .🤒

I just faced this right now. 
My all .MP4 uploaded as doc 🥺

### CODE REVIEW

**Comment by rking32** [comment]
@gautamajay52 why don't you use just `lower()` simple
anyway, it worked for your after doing this ?

**Comment by gautamajay52** [comment]
> @gautamajay52 why don't you use just `lower()` simple
> anyway, it worked for your after doing this ?

Actually I was uploading some video lectures from my gdrive to telegram using rclone.
And yes after this commit it started to upload .MP4 as video.

**Comment by gautamajay52** [comment]
> @gautamajay52 why don't you use just `lower()` simple
> anyway, it worked for your after doing this ?

And I don't see any problem in doing so.
May this be the better algo to check extension.

**Comment by rking32** [comment]
> > @gautamajay52 why don't you use just `lower()` simple
> > anyway, it worked for your after doing this ?
> 
> And I don't see any problem in doing so.
> May this be the better algo to check extension.

ok no problem. i suggested like this

**original**
```python
path.name.endswith((".mkv", ".mp4", ".webm"))
```
**suggestion**
```python
path.name.lower().endswith((".mkv", ".mp4", ".webm"))
```
**yours**
```python3
path.name.upper().endswith((".MKV", ".MP4", ".WEBM"))
```

can you fix [this](https://github.com/UsergeTeam/Userge/pull/149#issuecomment-687597501)
so i can merge this

**Comment by gautamajay52** [comment]
> > > @gautamajay52 why don't you use just `lower()` simple
> > > anyway, it worked for your after doing this ?
> > 
> > 
> > And I don't see any problem in doing so.
> > May this be the better algo to check extension.
> 
> ok no problem. i suggested like this
> 
> **original**
> 
> ```python
> path.name.endswith((".mkv", ".mp4", ".webm"))
> ```
> 
> **suggestion**
> 
> ```python
> path.name.lower().endswith((".mkv", ".mp4", ".webm"))
> ```
> 
> **yours**
> 
> ```python
> path.name.upper().endswith((".MKV", ".MP4", ".WEBM"))
> ```
> 
> can you fix [this](https://github.com/UsergeTeam/Userge/pull/149#issuecomment-687597501)
> so i can merge this

Yes sur 😬

**Comment by rking32** [comment]
@gautamajay52 how can we fix https://github.com/UsergeTeam/Userge/pull/149#issuecomment-687597501 (line too long)
like storing `path.name.upper()` to a variable 🤔

**Comment by gautamajay52** [comment]
> @gautamajay52 how can we fix [#149 (comment)](https://github.com/UsergeTeam/Userge/pull/149#issuecomment-687597501) (line too long)
> like storing `path.name.upper()` to a variable 🤔

Done 😕

**Comment by rking32** [comment]
> > @gautamajay52 how can we fix [#149 (comment)](https://github.com/UsergeTeam/Userge/pull/149#issuecomment-687597501) (line too long)
> > like storing `path.name.upper()` to a variable thinking
> 
> Done confused

nice

**Pull request merged**
