### PR TITLE
tools: utils: add get_media_path_and_name

### PR DESCRIPTION
**Pull request by yshalsager**
Moved from https://github.com/UsergeTeam/Userge-Plugins/blob/master/plugins/ff_mpeg.py#L56, since the same function can be used instead of having duplicated code in ffmpeg, [transcribe](https://github.com/UsergeTeam/Userge-Plugins/blob/master/plugins/transcribe.py#L127), and [google photos](https://github.com/UsergeTeam/Userge-Plugins/blob/master/plugins/google_photos.py#L123) modules.

### CODE REVIEW

**Comment by Krishna-Singhal** [comment]
Hii @yshalsager , your pull request seems useful but Unfortunately will not work in major update, cuz you are importing url_download and tg_doenload from download.py

**Comment by yshalsager** [comment]
> Hii @yshalsager , your pull request seems useful but Unfortunately will not work in major update, cuz you are importing url_download and tg_download from download.py

I see, just noticed that `userge` is defined in module `__init__`. 
I think we can use relative import, by replacing `userge.plugins.misc.download` with `..plugins.misc.download` and it should work.

**Comment by Krishna-Singhal** [comment]
> I see, just noticed that `userge` is defined in module `__init__`. I think we can use relative import, by replacing `userge.plugins.misc.download` with `..plugins.misc.download` and it should work.

No, you are not getting me, Userge core is upgrading to verison 1 where it is not necessary that download plugin is available or not, and in utils you are importing from download so this is a issue

**Comment by yshalsager** [comment]
> No, you are not getting me, Userge core is upgrading to verison 1 where it is not necessary that download plugin is available or not, and in utils you are importing from download so this is a issue

Ah, that's another thing. Feel free to either accept the PR, let it wait for the new changes, or reject it :D

**Pull request closed without merging**
