### PR TITLE
fix for incoming handlers for reaction

### PR DESCRIPTION
**Pull request by Krishna-Singhal**

### CODE REVIEW

**Comment by rking32** [comment]
did you test this? `m.reactions` always null for me

**Comment by Krishna-Singhal** [comment]
> did you test this? `m.reactions` always null for me

i tested, it's None when message doesn't contains reactions other return List of reactions

**Comment by rking32** [comment]
Let's say,

a sudo user sends the `!ping` command > triggers (`m.reactions` is `None`)
then he reacts to that message > doesn't trigger (`m.reactions` not `None`)
removes the reaction > triggers (`m.reactions` is `None`)

so how do handle the last case? shouldn't trigger r8?

**Comment by subinps** [comment]
> Let's say,
> 
> a sudo user sends the `!ping` command > triggers (`m.reactions` is `None`) then he reacts to that message > doesn't trigger (`m.reactions` not `None`) removes the reaction > triggers (`m.reactions` is `None`)
> 
> so how do handle the last case? shouldn't trigger r8?

Edited update is received only once. So when the user sends command , reactions are none, if once reacted it contains the reactions (only this time edited handler triggers) later if he removes the reactions again reactions are none but it won't trigger the command since no edited update will be received.

**Comment by Krishna-Singhal** [comment]
closing because of conflicts and no valid solution yet to handle that

**Pull request closed without merging**
